In [3]:
# Normalization Problem
import numpy as np                      # Imports NumPy library 

X = np.random.random((5, 5))            # Creates a 5x5 array with random floating point values 

mean = np.mean(X)                       # Calculates the average of the elements in the created array
std = np.std(X)                         # Calcuates the standard deviation of the array 

X = (X - mean) / std                    # Normalizes X 
print(X)                                # Prints X 
np.save('X_normalized.npy', X)          # Saves the NumPy array 

[[-0.94877624  1.37849769 -1.1929761  -2.24600106  0.79851006]
 [-1.03390308  0.6597996   0.08974712  1.43624399  1.36898711]
 [ 0.56514916 -0.2190846  -0.19540352  1.54987897  0.79384071]
 [ 0.78806155 -0.85866236 -0.73990502  0.88011281 -1.32853001]
 [-0.93428443 -0.42399008 -0.49554684  0.61017021 -0.30193564]]


In [4]:
array = np.load('X_normalized.npy')     # Loads array from the file attached
array                                   # Displays the array

array([[-0.94877624,  1.37849769, -1.1929761 , -2.24600106,  0.79851006],
       [-1.03390308,  0.6597996 ,  0.08974712,  1.43624399,  1.36898711],
       [ 0.56514916, -0.2190846 , -0.19540352,  1.54987897,  0.79384071],
       [ 0.78806155, -0.85866236, -0.73990502,  0.88011281, -1.32853001],
       [-0.93428443, -0.42399008, -0.49554684,  0.61017021, -0.30193564]])

In [4]:
# Divisible by 3 Problem

import numpy as np                               # Imports NumPy library 

C = np.arange(1, 101)                            # Create a 1D array with numbers from 1 to 100
B = C.reshape(10, 10)                            # Reshape the 1D array into a 10x10 2D array
A = B**2                                         # Squares every element in the array 

def find_divisible_by_3(A):                      # The elements are first checked whether they are divisible by 3. The array 
  return A * (A % 3 == 0)                        # is multiplied again. If True, elements are reatained that are divisible by 3, while elements 
                                                 # that are not divisible by 3 are replaced with 0
    
D = find_divisible_by_3(A)                       # Calls the function 
print("Square of first 100 positive integers: ")
print(A)
print("Elements divisible by 3: ")               # Dsiplays the array with elements that are divisible by 3
print(D)                                
np.save('div_by_3.npy', D)                       # Saves the NumPy array


Square of first 100 positive integers: 
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]
Elements divisible by 3: 
[[   0    0    9    0    0   36    0    0   81    0]
 [   0  144    0    0  225    0    0  324    0    0]
 [ 441    0    0  576    0    0  729    0    0  900]
 [   0    0 1089    0    0 1296    0    0 1521    0]
 [   0 1764    0    0 2025    0    0 2304    0    0]
 [2601    0    0 2916    0    0 3249  

In [5]:
array = np.load('div_by_3.npy')         # Loads array from the file attached
array                                   # Displays the array 

array([[   0,    0,    9,    0,    0,   36,    0,    0,   81,    0],
       [   0,  144,    0,    0,  225,    0,    0,  324,    0,    0],
       [ 441,    0,    0,  576,    0,    0,  729,    0,    0,  900],
       [   0,    0, 1089,    0,    0, 1296,    0,    0, 1521,    0],
       [   0, 1764,    0,    0, 2025,    0,    0, 2304,    0,    0],
       [2601,    0,    0, 2916,    0,    0, 3249,    0,    0, 3600],
       [   0,    0, 3969,    0,    0, 4356,    0,    0, 4761,    0],
       [   0, 5184,    0,    0, 5625,    0,    0, 6084,    0,    0],
       [6561,    0,    0, 7056,    0,    0, 7569,    0,    0, 8100],
       [   0,    0, 8649,    0,    0, 9216,    0,    0, 9801,    0]])