In [3]:
# Normalization Problem
import numpy as np                      # Imports NumPy library 

X = np.random.random((5, 5))            # Creates a 5x5 array with random floating point values 

mean = np.mean(X)                       # Calculates the average of the elements in the created array
std = np.std(X)                         # Calcuates the standard deviation of the array 

X = (X - mean) / std                    # Normalizes X 
print(X)                                # Prints X 
np.save('X_normalized.npy', X)          # Saves the NumPy array 

[[-0.94877624  1.37849769 -1.1929761  -2.24600106  0.79851006]
 [-1.03390308  0.6597996   0.08974712  1.43624399  1.36898711]
 [ 0.56514916 -0.2190846  -0.19540352  1.54987897  0.79384071]
 [ 0.78806155 -0.85866236 -0.73990502  0.88011281 -1.32853001]
 [-0.93428443 -0.42399008 -0.49554684  0.61017021 -0.30193564]]


In [4]:
array = np.load('X_normalized.npy')     # Loads array from the file attached
array                                   # Displays the array

array([[-0.94877624,  1.37849769, -1.1929761 , -2.24600106,  0.79851006],
       [-1.03390308,  0.6597996 ,  0.08974712,  1.43624399,  1.36898711],
       [ 0.56514916, -0.2190846 , -0.19540352,  1.54987897,  0.79384071],
       [ 0.78806155, -0.85866236, -0.73990502,  0.88011281, -1.32853001],
       [-0.93428443, -0.42399008, -0.49554684,  0.61017021, -0.30193564]])

In [6]:
# Divisible By 3 Problem 

import numpy as np                      # Imports NumPy library 

C = np.arange(1, 101)                   # Create a 1D array with numbers from 1 to 100
B = C.reshape(10, 10)                   # Reshape the 1D array into a 10x10 2D array
A = B**2                                # Squares every element in the array 

def find_divisible_by_3(A):             
  mask = (A % 3 == 0)                   # Create a boolean mask where True specifies elements that are divisible by 3
  D = A[mask]                           # Retrieves all elements divisible by 3
  result = np.zeros_like(A)             # Initializes the elements in the array with zeroes 
  result[mask] = A[mask]                # Retains the numbers divisible by 3 in the array and replace that don't with zeroes
  return result

D = find_divisible_by_3(A)              # Calls the function 
print("Elements divisible by 3: ")      # Dsiplays the array with elements that are divisible by 3
print(D)                                
np.save('div_by_3.npy', D)              # Saves the NumPy array


Elements divisible by 3: 
[[   0    0    9    0    0   36    0    0   81    0]
 [   0  144    0    0  225    0    0  324    0    0]
 [ 441    0    0  576    0    0  729    0    0  900]
 [   0    0 1089    0    0 1296    0    0 1521    0]
 [   0 1764    0    0 2025    0    0 2304    0    0]
 [2601    0    0 2916    0    0 3249    0    0 3600]
 [   0    0 3969    0    0 4356    0    0 4761    0]
 [   0 5184    0    0 5625    0    0 6084    0    0]
 [6561    0    0 7056    0    0 7569    0    0 8100]
 [   0    0 8649    0    0 9216    0    0 9801    0]]


In [5]:
array = np.load('div_by_3.npy')         # Loads array from the file attached
array                                   # Displays the array 

array([[   0,    0,    9,    0,    0,   36,    0,    0,   81,    0],
       [   0,  144,    0,    0,  225,    0,    0,  324,    0,    0],
       [ 441,    0,    0,  576,    0,    0,  729,    0,    0,  900],
       [   0,    0, 1089,    0,    0, 1296,    0,    0, 1521,    0],
       [   0, 1764,    0,    0, 2025,    0,    0, 2304,    0,    0],
       [2601,    0,    0, 2916,    0,    0, 3249,    0,    0, 3600],
       [   0,    0, 3969,    0,    0, 4356,    0,    0, 4761,    0],
       [   0, 5184,    0,    0, 5625,    0,    0, 6084,    0,    0],
       [6561,    0,    0, 7056,    0,    0, 7569,    0,    0, 8100],
       [   0,    0, 8649,    0,    0, 9216,    0,    0, 9801,    0]])