In [2]:
# Normalization Problem 

import numpy as np                      # Imports NumPy library 

X = np.random.random((5, 5))            # Creates a 5x5 array with random floating point values 

mean = np.mean(X)                       # Calculates the average of the elements in the created array
std = np.std(X)                         # Calcuates the standard deviation of the array 

X = (X - mean) / std                    # Normalizes X 
print(X)                                # Prints X 
np.save('X_normalized.npy', X)

[[-1.16164838 -1.9493291   0.15382725 -0.27037218  0.52124559]
 [-0.03091756 -0.88490522 -0.57976451  0.95624149 -1.48890419]
 [ 0.69629906  0.35381817 -0.16081637 -0.02353616 -1.64592207]
 [-0.40789905  0.51421424  1.27585275  1.19240384 -0.81840487]
 [ 1.27568931 -1.13122459  0.71871671  1.6926754   1.20266043]]


In [3]:
array = np.load('X_normalized.npy')
array

array([[-1.16164838, -1.9493291 ,  0.15382725, -0.27037218,  0.52124559],
       [-0.03091756, -0.88490522, -0.57976451,  0.95624149, -1.48890419],
       [ 0.69629906,  0.35381817, -0.16081637, -0.02353616, -1.64592207],
       [-0.40789905,  0.51421424,  1.27585275,  1.19240384, -0.81840487],
       [ 1.27568931, -1.13122459,  0.71871671,  1.6926754 ,  1.20266043]])